version: '3.8'

services:
  # Kafka and dependencies
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - rde-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - rde-network

  # MinIO object storage
  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - rde-network

  # Hive Metastore (required for Iceberg catalog)
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: metastore
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rde-network

  hive-metastore:
    image: apache/hive:3.1.3
    environment:
      SERVICE_NAME: metastore
      DB_DRIVER: postgres
      SERVICE_OPTS: "-Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver
                     -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://postgres:5432/metastore
                     -Djavax.jdo.option.ConnectionUserName=hive
                     -Djavax.jdo.option.ConnectionPassword=hive123"
    depends_on:
      - postgres
    ports:
      - "9083:9083"
    networks:
      - rde-network

  # Trino query engine
  trino:
    image: trinodb/trino:435
    ports:
      - "8080:8080"
    environment:
      - CATALOG_MANAGEMENT=dynamic
    volumes:
      - ./trino/etc:/etc/trino:ro
      - ./trino/catalog:/etc/trino/catalog:ro
    depends_on:
      - minio
      - hive-metastore
    networks:
      - rde-network

volumes:
  minio_data:
  postgres_data:

networks:
  rde-network:
    driver: bridge
