version: '3.8'

services:
  # Existing services from main docker-compose.yml
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  # Trino coordinator
  trino-coordinator:
    image: trinodb/trino:435
    ports:
      - "8080:8080"
    environment:
      - CATALOG_MANAGEMENT=dynamic
    volumes:
      - ./trino/etc:/etc/trino:ro
      - ./trino/catalog:/etc/trino/catalog:ro
    depends_on:
      - minio

  # Trino worker (optional - for scaling)
  trino-worker:
    image: trinodb/trino:435
    environment:
      - CATALOG_MANAGEMENT=dynamic
    volumes:
      - ./trino/etc:/etc/trino:ro
      - ./trino/catalog:/etc/trino/catalog:ro
    depends_on:
      - trino-coordinator

volumes:
  minio_data:
