name: kafka-to-iceberg-configured
sources:
  - type: kafka
    id: kafka-source
    brokers: localhost:9092
    group_id: rde-group-iceberg-configured
    topic: sales
    schema:
      auto_infer: true  # Still allow new fields to be inferred
      fields:
        - name: id
          data_type: int64
          nullable: false
        - name: amount
          data_type: float64
          nullable: true
        - name: product
          data_type: string
          nullable: true
        - name: timestamp
          data_type: string
          nullable: true

transforms:
  - type: passthrough
    id: clean

sinks:
  - type: iceberg
    id: iceberg-sink
    table_name: sales_table_configured
    bucket: iceberg-bucket
    endpoint: http://localhost:9000
    access_key: minioadmin
    secret_key: minioadmin
    region: us-east-1

edges:
  - [kafka-source, clean]
  - [clean, iceberg-sink]
