name: "crypto-realtime-pipeline"
description: "Real-time blockchain and crypto news data pipeline"

# Global configuration
config:
  kafka:
    brokers: "localhost:9092"
    replication_factor: 1
    partitions: 3

  storage:
    endpoint: "http://localhost:9000"
    access_key: "minioadmin"
    secret_key: "minioadmin"
    region: "us-east-1"

  processing:
    batch_size: 1000
    auto_schema_evolution: true
    data_cleaning: true

# Data sources
sources:
  # Bitcoin market data source
  - type: kafka
    id: "bitcoin-market-source"
    brokers: "localhost:9092"
    group_id: "rde-bitcoin-market-group"
    topic: "bitcoin-market"
    schema:
      auto_infer: true

  # Crypto news data source
  - type: kafka
    id: "crypto-news-source"
    brokers: "localhost:9092"
    group_id: "rde-crypto-news-group"
    topic: "crypto-news"
    schema:
      auto_infer: true

# Data transformations
transforms:
  # Bitcoin market data cleaning
  - type: clean_data
    id: "clean-bitcoin-market"
    remove_nulls: true
    trim_strings: true

  # Bitcoin market data enrichment
  - type: sql_transform
    id: "enrich-bitcoin-market"
    query: |
      SELECT 
        *,
        CURRENT_TIMESTAMP as ingestion_time,
        DATE(timestamp) as partition_date,
        EXTRACT(HOUR FROM timestamp) as partition_hour,
        CASE 
          WHEN price_change_24h > 0 THEN 'bullish'
          WHEN price_change_24h < 0 THEN 'bearish'
          ELSE 'neutral'
        END as market_sentiment,
        ROUND(volume_24h / 1000000, 2) as volume_millions
      FROM input_data
      WHERE price IS NOT NULL AND timestamp IS NOT NULL

  # Crypto news data cleaning
  - type: clean_data
    id: "clean-crypto-news"
    remove_nulls: true
    trim_strings: true
    normalize_case: "lower"

  # Crypto news data enrichment
  - type: sql_transform
    id: "enrich-crypto-news"
    query: |
      SELECT 
        *,
        CURRENT_TIMESTAMP as ingestion_time,
        DATE(published_at) as partition_date,
        EXTRACT(HOUR FROM published_at) as partition_hour,
        CASE 
          WHEN sentiment_score > 0.3 THEN 'positive'
          WHEN sentiment_score < -0.3 THEN 'negative'
          ELSE 'neutral'
        END as sentiment_category,
        ARRAY_LENGTH(keywords) as keyword_count,
        CASE 
          WHEN source IN ('coindesk', 'cointelegraph', 'bitcoin.com') THEN 'major'
          WHEN source IN ('cryptopanic', 'cryptonews') THEN 'aggregator'
          ELSE 'other'
        END as source_category
      FROM input_data
      WHERE title IS NOT NULL AND published_at IS NOT NULL

# Data sinks
sinks:
  # Bitcoin market data sink
  - type: iceberg
    id: "bitcoin-market-sink"
    table_name: "bitcoin_market_data"
    bucket: "crypto-data"
    endpoint: "http://localhost:9000"
    access_key: "minioadmin"
    secret_key: "minioadmin"
    region: "us-east-1"

  # Crypto news data sink
  - type: iceberg
    id: "crypto-news-sink"
    table_name: "crypto_news_data"
    bucket: "crypto-data"
    endpoint: "http://localhost:9000"
    access_key: "minioadmin"
    secret_key: "minioadmin"
    region: "us-east-1"

# Pipeline connections
edges:
  # Bitcoin market data flow
  - ["bitcoin-market-source", "clean-bitcoin-market"]
  - ["clean-bitcoin-market", "enrich-bitcoin-market"]
  - ["enrich-bitcoin-market", "bitcoin-market-sink"]

  # Crypto news data flow
  - ["crypto-news-source", "clean-crypto-news"]
  - ["clean-crypto-news", "enrich-crypto-news"]
  - ["enrich-crypto-news", "crypto-news-sink"]
